# Shared or node-specific params
sensor_bridge:
  ros__parameters:
    port: "/dev/serial/by-id/usb-Silicon_Labs_ESP_TTL_2_ESP_TTL_2-if00-port0"
    #baudrate: 115200

motor_bridge:
  ros__parameters:
    port: "/dev/serial/by-id/usb-1a86_USB_Single_Serial_54A7002607-if00"
    #baudrate: 115200

scroll_approach_controller:
  ros__parameters:
    forward_distance: 1.0
    lateral_distance: 1.0
    distance_threshold: 0.08
    lateral_tolerance: 0.15
    max_forward_vel: 0.4
    max_lateral_vel: 0.4
    kp_x: 1.0
    ki_x: 0.0
    kd_x: 0.1
    kp_y: 0.8
    ki_y: 0.0
    kd_y: 0.08